# ADMUX Prometheus配置

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'admux-monitoring'

rule_files:
  # - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # ADX服务器监控
  - job_name: 'admux-adx-server'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Tracking服务器监控
  - job_name: 'admux-tracking-server'
    static_configs:
      - targets: ['host.docker.internal:8081']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # 系统监控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Grafana监控
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s