# ADMUX监控服务 Docker Compose配置
version: '3.8'

services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: admux-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ../conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - admux-monitoring
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Prometheus监控
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: admux-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ../conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    networks:
      - admux-monitoring
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy

  # Grafana可视化
  grafana:
    image: grafana/grafana:10.1.0
    container_name: admux-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ../conf/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../conf/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - admux-monitoring
    restart: unless-stopped
    depends_on:
      - prometheus

  # Redis Exporter (Redis监控)
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: admux-redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - admux-monitoring
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy

  # Node Exporter (系统监控)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: admux-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - admux-monitoring
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  admux-monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16